# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'
set -g set-clipboard on
set -g allow-passthrough all
set -g mouse on
set -g extended-keys on
set -g extended-keys-format csi-u
set -g @catppuccin_flavour 'mocha' # or latte, frappe, macchiato
set -g default-terminal "tmux-256color"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Remap prefix from 'C-b' to 'C-Space'
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Bindings for tmux-fzf plugin
bind-key w run-shell -b "~/.tmux/plugins/tmux-fzf/scripts/window.sh switch"
bind-key s run-shell -b "~/.tmux/plugins/tmux-fzf/scripts/session.sh switch"

# Open splits in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

