#!/usr/bin/env zsh

# Piped stdin has no script directory; sibling .zshrc means we are in a checkout.
# ${0:A:h} is the script's absolute directory (:A realpath, :h dirname).
here=${0:A:h}
if [[ -f $0 && -f $here/.zshrc ]]; then
	src=$here
	rsync_opts=(-av)
else
	src=$(mktemp -d)
	trap "rm -rf ${(q)src}" EXIT
	git clone --depth 1 https://github.com/joostm1/home-sweet-home.git "$src"
	rsync_opts=(-a)
fi

rsync "${rsync_opts[@]}" --exclude .git --exclude .gitignore --exclude README.md --exclude install "$src/" "$HOME/"

XDG_DATA_HOME=$HOME/.local/share
XDG_BIN=$XDG_DATA_HOME/../bin # where xdg aware tools install binaries
ZSH=$HOME/.oh-my-zsh
FZF_BASE=$HOME/.fzf
NVM_DIR=$HOME/.nvm

# fetch favorites
## oh-my
[[ ! -d $ZSH ]] && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc
## syntax highlighting
[[ ! -d $ZSH/custom/plugins/zsh-syntax-highlighting ]] && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH/custom/plugins/zsh-syntax-highlighting
## autosuggestions
[[ ! -d $ZSH/custom/plugins/zsh-autosuggestions ]] && git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH/custom/plugins/zsh-autosuggestions
## Fuzzy finder
[[ ! -d $FZF_BASE ]] && git clone --depth 1 https://github.com/junegunn/fzf.git $FZF_BASE && $FZF_BASE/install --bin --no-update-rc --no-bash --no-fish
## uv
[[ ! -x $XDG_BIN/uv ]] && curl -LsSf https://astral.sh/uv/install.sh | sh
UV_TOOL_DIR=$($XDG_BIN/uv tool dir)
## opencode
[[ ! -x $HOME/.opencode/bin/opencode ]] && curl -fsSL https://opencode.ai/install | bash
## zoxide directory jumper
[[ ! -x $XDG_BIN/zoxide ]] && curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
## snow cli
[[ ! -z $UV_TOOL_DIR ]] && [[ ! -d $UV_TOOL_DIR/snowflake-cli ]] && $XDG_BIN/uv tool install snowflake-cli
## dbt-core -- who can go without it?
[[ ! -z $UV_TOOL_DIR ]] && [[ ! -d $UV_TOOL_DIR/dbt-core ]] && $XDG_BIN/uv tool install dbt-core --with dbt-postgres,dbt-snowflake --python 3.13 && ln -fs $UV_TOOL_DIR/dbt-core/bin/dbt $XDG_BIN/dbt-core
## tmux plugins
[[ ! -d $HOME/.tmux/plugins/tpm ]] && git clone https://github.com/tmux-plugins/tpm.git $HOME/.tmux/plugins/tpm && $HOME/.tmux/plugins/tpm/bin/install_plugins
## node version manager
[[ ! -d $NVM_DIR ]] && git clone https://github.com/nvm-sh/nvm.git $NVM_DIR

# Last [[ is false when that tool already exists; without this the script exits 1.
:
